version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully again
artifacts:
  files:
    - target/PMC-1.0.0.jar
  discard-paths: yes