spring:
  application:
    name: PMC Application
  jackson:
    default-property-inclusion: non_null
  main:
    banner-mode: "off"
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    contextPath: /bill

aws:
  region: ap-south-1
  dynamodb:
    endpoint: https://dynamodb.ap-south-1.amazonaws.com
    accessKey: AKIAQ4ZN5LSWHSB5B4JK
    secretKey: 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