spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pmc
  application:
    name: PMC Application
  jackson:
    default-property-inclusion: non_null
  main:
    banner-mode: "off"
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    contextPath: /bill

aws:
  region: ap-south-1
  dynamodb:
    endpoint: https://dynamodb.ap-south-1.amazonaws.com
    accessKey: AKIAQ4ZN5LSWDR6VHCQ6
    secretKey: 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