package com.ravalparth.pmc.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "perfect")
public class Customer {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String invoiceNo;

    @DynamoDBAttribute
    private String customerName;

    @DynamoDBAttribute
    private String customerAddress;

    @DynamoDBAttribute
    private String customerGstNo;

    @DynamoDBAttribute
    private String invoiceDate;

    @DynamoDBAttribute
    private String vehicleNo;

    @DynamoDBAttribute
    private String dispatch;

    @DynamoDBAttribute
    private String particulars;

    @DynamoDBAttribute
    private int hsnNo;

    @DynamoDBAttribute
    private int qty;

    @DynamoDBAttribute
    private double rate;

    @DynamoDBAttribute
    private double amount;

    @DynamoDBAttribute
    private double taxAmount;

    @DynamoDBAttribute
    private double totalAmount;

    @DynamoDBAttribute
    private String fileName;

    @DynamoDBAttribute
    @JsonIgnore
    private byte[] bill;
}
